### ISSUE TITLE
Exception during automation: 'SERVICE_ACCOUNT'

### ISSUE THREAD

**Issue by SamyCoenen** [stacklio/stackl#102]
# Expected Result

Job is received by agent and automation job is created on Kubernetes.

# Actual Result

The STACKL agent receives the job but is unable to create the job.

# Steps To Reproduce

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: stackl-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stackl-agent
    app.kubernetes.io/version: 0.1.0
    component: agent
    helm.sh/chart: stackl-agent-0.1.1
  name: stackl-agent-agent
  namespace: stackl-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: stackl-agent
      app.kubernetes.io/name: stackl-agent
      component: agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: stackl-agent
        app.kubernetes.io/name: stackl-agent
        component: agent
    spec:
      containers:
      - env:
        - name: STACKL_HOST
          value: 52.31.122.113:31771
        - name: STACKL_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        - name: SECRET_HANDLER
          value: vault
        - name: AGENT_ID
          value: production-eks
        - name: STACKL_GRPC_HOST
          value: 52.31.122.113:32520
        - name: AGENT_SELECTOR
          value: production.*.*
        - name: VAULT_ADDR
          value: https://secrets.d.dome.dev
        - name: VAULT_ROLE
          value: stackl-eks
        image: stacklio/stackl-kubernetes-agent:v0.1.2
        imagePullPolicy: Always
        name: stackl-agent
        resources:
          requests:
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: stackl-agent-agent-stackl-agent
      serviceAccountName: stackl-agent-agent-stackl-agent
      terminationGracePeriodSeconds: 30
```

# Potential Causes, Fixes or Additional Information

```shell
starting kubernetes agent to 52.31.122.113:32520
Connected to STACKL with gRPC at 52.31.122.113:32520
Job received from STACKL through gRPC stream
Exception during automation: 'SERVICE_ACCOUNT
```
