### ISSUE TITLE
Multiple services with the same name in SAT result in single host

### ISSUE THREAD

**Issue by SamyCoenen** [stacklio/stackl#116]
# Expected Result

Every service in a SAT results in different groups and hosts in the Ansible inventory.

# Actual Result

With SAT:
```yaml
category: configs
description: ''
name: ct_k8s_vault2
policies: {}
services:
- ct_k8s_vault
- ct_k8s_vault
- ct_k8s_vault
- ct_k8s_vault2
type: stack_application_template
```
Only a single host ct_k8s_vault_0 is generated.

# Steps To Reproduce

See above

# Potential Causes, Fixes or Additional Information
