### ISSUE TITLE
Move "ansible_playbook_path" from provisioning params to invocation

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#192]
# Expected Result

When specifying 2 functional requirements that each have a playbook you want to run in the same service/stack-instance, both playbooks need to either be put in the same path or it is not possible to specify a playbook for both fr's.

```
params:
  ansible_connection: local
  ansible_playbook_path: /opt/ansible/roles/nw_ipam_infoblox/playbook.yml
```

```
params:
  ansible_connection: local
  ansible_playbook_path: /opt/ansible/roles/nw_dns_infoblox/playbook.yml
```

Only one of the above `ansible_playbook_path` will be added to the stack-instance.

# Potential Causes, Fixes or Additional Information

To avoid this problem, we should move this parameters to the invocation field, so each fr can have their playbook in a path of their choosing.

For example:

```
invocation:
  generic:
    as_group: false
    ansible_playbook_path: /opt/ansible/roles/nw_ipam_infoblox/playbook.yml
    before_command: null
    description: Creates DNS records on Infoblox
    image: docker-registry.antwerpen.be/platform/avi/ansible/roles/nw_dns_infoblox:feature-multi-instance
    tool: ansible
```
