### ISSUE TITLE
Ansible group specific parameters

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#210]
# Description of feature 

Have specific parameters per Ansible group

# Purpose of this new feature

Some Ansible groups require specific parameters. 

Following example could be a solution:

```
stackl_inventory_groups:
   - tags: ["k8s_worker"]
     description: ""
     count: 1
     params:
       voorbeeld: voorbeeld 
```

This requires changes in the Stackl inventory plugin
