### ISSUE TITLE
add ability to pass ENV vars

### ISSUE THREAD

**Issue by openPablo** [stacklio/stackl#226]
# Description of feature 
Add the ability to pass environment variables through stackl parameters
# Purpose of this new feature
Pass these env variables to container images.
# Additional information

**Comment by mieel** [comment]
A use case would be when we are already using a central config manager.

We could then define a environment agnostic stack config:
```
...
params:
  domain: ${Product.App.Common.Domain}
  central_logger: ${Operations.Logger}
```
