### ISSUE TITLE
Have multiple targets per service

### ISSUE THREAD

**Issue by GBrawl** [stacklio/stackl#68]
# Description of feature 

A service should be able to have multiple infrastructure targets, with our current stack-instance model this is not possible, so we'll have to change it.

# Purpose of this new feature

Be able to have multiple infrastructure targets

# Additional information

We should not take the first one here and take every possible target:

https://github.com/stacklio/stackl/blob/master/stackl/application/handler/stack_handler.py#L52

The current format is like this:

```
category: items
deleted: false
name: stack-instance
services:
  windows_2019:
    infrastructure_target: aws.brussels.eu-west
    provisioning_parameters:
      key: value
      win_domains:
      - domain_name: nubera.local
        state: domain
    secrets:
      password: PASS
      user: USER
type: stack_instance
```

We could change it to this:

```
category: items
deleted: false
name: stack-instance
services:
  windows_2019:
    aws.ireland.eu-west1:
      provisioning_parameters:
        key: value
        win_domains:
          state: domain
      secrets:
        password: PASS
        user: USER
    aws.ireland.eu-west2:
      provisioning_parameters:
        key: value
        win_domains:
          state: domain
      secrets:
        password: PASS
        user: USER
type: stack_instance
```
