### ISSUE TITLE
Decouple functional requirements from cloud providers

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#87]
# Description of feature 

When a VM is deployed with Terraform for example, OPA chooses the infrastructure target based on policies. However, when deploying to a certain infrastructure target, you need to use the correct image, and images are coupled to a functional requirement.

# Purpose of this new feature

Purpose of this feature is to decouple images from functional requirements a bit. Instead of creating a functional requirement per cloud provider, we propose to have one functional requirement with images coupled to a certain cloud provider. For example:

```yaml
invocation:
  description: Deploys VM
  image: 
    aws: repo.example.com/terraform/plans/tf_plan_vm_aws:v1.0.0
    vsphere: repo.example.com/terraform/plans/tf_plan_vm_vsphere:v1.0.0
```

A SIT would look something like this:

```yaml
- environment: acceptance
  location: belgium
  zone: dome_vsphere
  cloud_provider: vsphere
```
