### ISSUE TITLE
Ansible inventory script

### ISSUE THREAD

**Issue by stgrace** [stacklio/stackl#97]
# Expected Result

Ansible inventory script should be able to read secrets and pass it as host variables

# Actual Result

Ansible script does not read any secrets

# Steps To Reproduce

Create a stack instance with secrets using any secret handler. Try out the script with the following inventory file:

```yaml
---
plugin: stackl
host: stackl.example.com
stack_instance: instance_name
vault_token_path: "/path/to/vault-token"
vault_addr: https://vault.example.com
secret_handler: vault
```

# Potential Causes, Fixes or Additional Information

Rework of the base document could have broken this line:
```python
                    if hasattr(si_service, "secrets"):
```

The code probably never enters this if statement anymore
